version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      netfilter:
        patterns:
          - "github.com/florianl/go-nfqueue*"
          - "github.com/coreos/go-iptables"
      cli:
        patterns:
          - "github.com/spf13/*"
      packets:
        patterns:
          - "github.com/nblair2/go-dnp3*"
          - "github.com/gopacket/gopacket"
