version: 2

project_name: dingopie

before:
  hooks:
    - go mod tidy

builds:
  - &default_build
    id: default
    env:
      - CGO_ENABLED=0
    # Trick goreleaser into using garble as the build tool
    tool: garble
    command: "-literals"
    flags:
      # Makefile and ci should both set and record the GARBLE_SEED
      - -seed={{ envOrDefault "GARBLE_SEED" "random" }}
      - build
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/nblair2/dingopie/cmd.version={{.Version}}
      - -X github.com/nblair2/dingopie/cmd.commit={{.Commit}}
      - -X github.com/nblair2/dingopie/cmd.date={{.Date}}
    goos:
      - linux
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64
    go386: [ sse2 ]
    goarm: [ "7" ]
    ignore:
      # https://github.com/golang/go/issues/70705
      - goos: windows
        goarch: arm


  - <<: *default_build
    id: 386-softfloat
    goarch: [ "386" ]
    go386: [ softfloat ]

archives:
  - &default_archive
    id: default
    ids: [ default ]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
      {{- with .Arm }}v{{ . }}{{ end }}
      {{- with .I386 }}_{{ . }}{{ end }}
    formats:
      - gz
    format_overrides:
      - goos: windows
        formats: [ zip ]
    files:
      - none*

  - <<: *default_archive
    id: 386-softfloat
    ids:  [386-softfloat]

release:
  draft: false
  prerelease: false
  make_latest: true
  footer: |
    ---
    Garble Seed: `{{ .Env.GARBLE_SEED }}`

changelog:
  groups:
    - title: Breaking Changes
      regexp: '^.*!:'
      order: 0
    - title: Documentation
      regexp: '^doc'
      order: 1
    - title: Features
      regexp: '^feat'
      order: 2
    - title: Bug Fixes
      regexp: '^fix'
      order: 3
    - title: Performance Improvements
      regexp: '^perf'
      order: 4
    - title: Refactoring
      regexp: '^refac'
      order: 5
    - title: Testing, Builds, CI
      regexp: '^(test|build|ci)'
      order: 6
    - title: Other Changes
      order: 999
