# test this file with `make release`
version: 2

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    flags:
      - -trimpath
    goos:
      - linux
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64
      - ppc64le
      - mips
      - mipsle
      - mips64
      - mips64le
    goarm:
      - "5"
      - "6"
      - "7"
    gomips:
      - hardfloat
      - softfloat
    ignore:
      # https://github.com/golang/go/issues/70705
      - goos: windows
        goarch: arm

archives:
  - formats:
      - gz
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - none*

release:
  draft: false
  prerelease: false
  make_latest: true

changelog:
  disable: true
